import { HelpButton } from "help_button.slint";
import { InfoPopup } from "info_popup.slint";

export component HelpPopup inherits Rectangle {
    in property <string> help-text;

    button := HelpButton {
        clicked => {
            popup.show();
        }
    }

    popup := InfoPopup {
        x: button.x + button.width + 5px;
        y: button.y + 0px;

        info-text <=> help-text;
    }
}
