import { VerticalBox, Palette } from "std-widgets.slint";

export component InfoPopup inherits PopupWindow {
    in property <string> info-text;

    close-policy: close-on-click-outside;

    // Das visuelle Kästchen im Popup
    Rectangle {
        x: 0px;
        y: 0px;

        width: layout.preferred-width;
        height: layout.preferred-height;
        background: Palette.color-scheme == ColorScheme.dark ? darkslategray : whitesmoke;
        border-radius: 6px;
        border-width: 1px;
        border-color: Colors.darkgray;

        layout := VerticalBox {
            padding: 8px;

            Text {
                text: root.info-text;
                color: Palette.foreground;
                font-size: 13px;
                max-width: 200px;
                wrap: word-wrap;
            }
        }
    }
}
