/**
 * Copyright (C) 2026 ZIMO Elektronik
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published
 * by the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program. If not, see <https://gnu.org>.
 *
 *
 *
 *
 *
 * Option level selector component
 *
 * \file    ui/utility/option-level-selector/option-level-selector.slint
 * \author  Jonas Gahlert
 * \date    01.10.2026
 */

import { ComboBox } from "std-widgets.slint";
import { OptionLevel } from "option-level.slint";
export { OptionLevel } // Re-export

export component OptionLevelSelector inherits Rectangle {
    in-out property <OptionLevel> selected-level;

    preferred-height: box.preferred-height;
    preferred-width: box.preferred-width;

    box := ComboBox {
        model: [@tr("Basic"), @tr("Advanced"), @tr("Expert")];
        init => {
            self.current-index = root.selected-level == OptionLevel.Basic ? 0 : root.selected-level == OptionLevel.Advanced ? 1 : 2;
        }
        selected => {
            root.selected-level = self.current-index == 0 ? OptionLevel.Basic : self.current-index == 1 ? OptionLevel.Advanced : OptionLevel.Expert;
        }
    }
}
