/**
 * Copyright (C) 2026 ZIMO Elektronik
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published
 * by the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program. If not, see <https://gnu.org>.
 *
 *
 *
 *
 *
 * Step text mapping component
 *
 * \file    ui/progress/dynamic/step-text.slint
 * \author  Jonas Gahlert
 * \date    01.10.2026
 */

export enum MessageIDAdapter {
    Start,
    StartComplete,
    Init,
    InitComplete,
    SearchDecoder,
    FoundDecoder,
    EraseFlash,
    EraseFlashComplete,
    WriteFlash,
    WriteFlashComplete,
    ReadCv,
    ReadCvComplete,
    WriteCv,
    WriteCvComplete,
    Verify,
    VerifyComplete,
    VerifyError,
    Cleanup,
    CleanupComplete,
    Done,
    Abort,
    AbortDevice,
    AbortInit,
    AbortDecoderSearch,
    AbortFlashErase,
    AbortFlashWrite,
    AbortVerify,
    AbortUnresponsive,
    Default,
}

export component StepText inherits Text {
    in property <MessageIDAdapter> id;

    font-size: 14px;
    font-weight: 700;

    text: id == MessageIDAdapter.Start ? @tr("Start") :
        id == MessageIDAdapter.StartComplete ? @tr("Started") :
        id == MessageIDAdapter.Init ? @tr("Initializing") :
        id == MessageIDAdapter.InitComplete ? @tr("Finished Initializing") :
        id == MessageIDAdapter.SearchDecoder ? @tr("Search for decoder") :
        id == MessageIDAdapter.FoundDecoder ? @tr("Found decoder") :
        id == MessageIDAdapter.EraseFlash ? @tr("Erase Flash") :
        id == MessageIDAdapter.EraseFlashComplete ? @tr("Erased Flash") :
        id == MessageIDAdapter.WriteFlash ? @tr("Writing Flash") :
        id == MessageIDAdapter.WriteFlashComplete ? @tr("Written Flash") :
        id == MessageIDAdapter.ReadCv ? @tr("Reading CVs") :
        id == MessageIDAdapter.ReadCvComplete ? @tr("Finished reading CVs") :
        id == MessageIDAdapter.WriteCv ? @tr("Writing CVs") :
        id == MessageIDAdapter.WriteCvComplete ? @tr("Finished writing CVs") :
        id == MessageIDAdapter.Verify ? @tr("Verifying") :
        id == MessageIDAdapter.VerifyComplete ? @tr("Successfully verified") :
        id == MessageIDAdapter.VerifyError ? @tr("Error during verification") :
        id == MessageIDAdapter.Cleanup ? @tr("Perform cleanup") :
        id == MessageIDAdapter.CleanupComplete ? @tr("Cleanup complete") :
        id == MessageIDAdapter.Done ? @tr("Done") :
        id == MessageIDAdapter.Abort ? @tr("Aborted") :
        id == MessageIDAdapter.AbortDevice ? @tr("No device found") :
        id == MessageIDAdapter.AbortInit ? @tr("Unable to setup process") :
        id == MessageIDAdapter.AbortDecoderSearch ? @tr("No decoder found") :
        id == MessageIDAdapter.AbortFlashErase ? @tr("Unable to erase flash") :
        id == MessageIDAdapter.AbortFlashWrite ? @tr("Unable to write flash") :
        id == MessageIDAdapter.AbortVerify ? @tr("Error during verification") :
        id == MessageIDAdapter.AbortUnresponsive ? @tr("Update device filed to respond") : @tr("Imagine a helpful string here");
}
