/**
 * Copyright (C) 2026 ZIMO Elektronik
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published
 * by the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program. If not, see <https://gnu.org>.
 *
 *
 *
 *
 *
 * Help button component
 *
 * \file    ui/utility/help-popup/help-button.slint
 * \author  Jonas Gahlert
 * \date    01.10.2026
 */

import { Palette } from "std-widgets.slint";
export component HelpButton inherits Rectangle {
    in property <length> size: 16px;

    callback clicked();

    width: root.size;
    height: root.size;

    border-radius: root.size / 2;

    background: Palette.color-scheme == ColorScheme.dark ? (ta.pressed ? Colors.maroon : (ta.has-hover ? Colors.crimson : Colors.tomato)) : (ta.pressed ? Colors.midnightblue : (ta.has-hover ? Colors.royalblue : Colors.cornflowerblue));
    animate background { duration: 150ms; }

    Text {
        text: "?";
        font-size: root.size * 0.75;
        font-weight: 700;
        color: white;
        vertical-alignment: center;
        horizontal-alignment: center;
    }

    ta := TouchArea {
        clicked => {
            root.clicked();
        }
        mouse-cursor: pointer; // Change cursor when hovering
    }
}
