/**
 * Copyright (C) 2026 ZIMO Elektronik
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published
 * by the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program. If not, see <https://gnu.org>.
 *
 *
 *
 *
 *
 * Help popup component
 *
 * \file    ui/utility/help-popup/help-popup.slint
 * \author  Jonas Gahlert
 * \date    01.10.2026
 */

import { HelpButton } from "help-button.slint";
import { InfoPopup } from "info-popup.slint";

export component HelpPopup inherits Rectangle {
    in property <string> help-text;

    button := HelpButton {
        clicked => {
            popup.show();
        }
    }

    popup := InfoPopup {
        x: button.absolute-position.x - root.absolute-position.x + button.width + 5px;
        y: button.absolute-position.y - root.absolute-position.y;

        info-text <=> help-text;
    }
}
