/**
 * Copyright (C) 2026 ZIMO Elektronik
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published
 * by the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program. If not, see <https://gnu.org>.
 *
 *
 *
 *
 *
 * Help mode button component
 *
 * \file    ui/utility/help-popup/help-mode-button.slint
 * \author  Jonas Gahlert
 * \date    01.10.2026
 */

import { HelpButton } from "help-button.slint";

export component HelpModeButton inherits Rectangle {
    in-out property <bool> help-mode;

    width: button.width;

    button := HelpButton {
        size: 20px;

        clicked => {
            root.help-mode = !root.help-mode;
        }
    }
}
