import { Palette } from "std-widgets.slint";
export component HelpButton inherits Rectangle {
    in property <length> size: 16px;

    callback clicked();

    width: root.size;
    height: root.size;

    border-radius: root.size / 2;

    background: Palette.color-scheme == ColorScheme.dark ? (ta.pressed ? Colors.maroon : (ta.has-hover ? Colors.crimson : Colors.tomato)) : (ta.pressed ? Colors.midnightblue : (ta.has-hover ? Colors.royalblue : Colors.cornflowerblue));
    animate background { duration: 150ms; }

    Text {
        text: "?";
        font-size: root.size * 0.75;
        font-weight: 700;
        color: white;
        vertical-alignment: center;
        horizontal-alignment: center;
    }

    ta := TouchArea {
        clicked => {
            root.clicked();
        }
        mouse-cursor: pointer; // Change cursor when hovering
    }
}
