/**
 * Copyright (C) 2026 ZIMO Elektronik
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published
 * by the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program. If not, see <https://gnu.org>.
 *
 *
 *
 *
 *
 * Info popup component
 *
 * \file    ui/utility/help-popup/info-popup.slint
 * \author  Jonas Gahlert
 * \date    01.10.2026
 */

import { VerticalBox, Palette } from "std-widgets.slint";

export component InfoPopup inherits PopupWindow {
    in property <string> info-text;

    close-policy: close-on-click-outside;

    Rectangle {
        x: 0px;
        y: 0px;

        width: layout.preferred-width;
        height: layout.preferred-height;
        background: Palette.color-scheme == ColorScheme.dark ? darkslategray : whitesmoke;
        border-radius: 6px;
        border-width: 1px;
        border-color: Colors.darkgray;

        layout := VerticalBox {
            padding: 8px;

            Text {
                text: root.info-text;
                color: Palette.foreground;
                font-size: 13px;
                max-width: 200px;
                wrap: word-wrap;
            }
        }
    }
}
