import { ListView, VerticalBox } from "std-widgets.slint";
import { CvRow } from "cv_row.slint";
import { Cv } from "cv.slint";

export component CvList inherits VerticalLayout {
    in property <[Cv]> cv-list;

    callback data_changed(int, Cv);

    padding: 10px;
    Text {
        text: "Liste von Cvs";
    }

    ListView {
        preferred-height: dummy-row.preferred-height * Math.min(root.cv-list.length, 5);
        preferred-width: dummy-row.preferred-width;

        for single-cv[idx] in cv-list: CvRow {
            cv: single-cv;
            is-even: Math.mod(idx, 2) == 0;
            toggled(checked) => {
                single-cv.selected = checked;
                root.data_changed(idx, single-cv)
            }
        }
    }

    dummy-row := CvRow {
        visible: false;
    }
}
