import { Cv } from "cv.slint";
import { CheckBox, HorizontalBox } from "std-widgets.slint";

export component CvRow inherits Rectangle {
    in property <Cv> cv;
    in property <bool> is-even;

    callback toggled(bool);

    background: root.is-even ? #f9f9f9 : #eeeeee;
    border-radius: 4px;

    preferred-height: layout.preferred-height;
    preferred-width: layout.preferred-width;

    layout := HorizontalLayout {
        alignment: LayoutAlignment.start;
        spacing: 10px;
        padding: 5px;

        checkbox := CheckBox {
            checked: root.cv.selected;
            toggled => {
                root.toggled(self.checked)
            }
        }

        Text {
            width: 30px;
            text: root.cv.address;
            font-size: 14px;
        }

        Text {
            width: 30px;
            text: root.cv.value;
            font-size: 14px;
        }

        Text {
            width: 100px;
            text: root.cv.name;
            font-size: 14px;
        }

        Text {
            width: 150px;
            text: root.cv.description;
            font-size: 11px;
            color: #666;
        }
    }
}
