/**
 * Copyright (C) 2026 ZIMO Elektronik
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published
 * by the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program. If not, see <https://gnu.org>.
 *
 *
 *
 *
 *
 * Mode selector component
 *
 * \file    ui/soundload/mode-selector.slint
 * \author  Jonas Gahlert
 * \date    01.10.2026
 */

import { SoundLoadMode } from "mode.slint";
import { ComboBox } from "std-widgets.slint";
export { SoundLoadMode }
export component ModeSelector {
    in-out property <SoundLoadMode> selected-mode;

    HorizontalLayout {
        alignment: start;
        spacing: 10px;

        Text {
            text: @tr("Mode");
            font-size: 16px;
            vertical-alignment: center;
        }

        ComboBox {
            model: [@tr("SUSI"), @tr("Track")];

            selected => {
                root.selected-mode = self.current-index == 0 ? SoundLoadMode.ZUSI : SoundLoadMode.MDU;
            }
        }
    }
}
