/**
 * Copyright (C) 2026 ZIMO Elektronik
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published
 * by the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program. If not, see <https://gnu.org>.
 *
 *
 *
 *
 *
 * Project info component
 *
 * \file    ui/soundload/project-info.slint
 * \author  Jonas Gahlert
 * \date    01.10.2026
 */

import { VerticalBox, Palette } from "std-widgets.slint";
export component ProjectInfoPanel inherits Rectangle {
    in property <string> name;
    in property <string> author;
    in property <string> email;

    height: 150px;
    width: 350px;

    background: Palette.alternate-background;

    VerticalLayout {
        alignment: start;
        padding: 4px;
        Text {
            text: @tr("Project information");
            font-size: 20px;
        }

        VerticalBox {
            padding: 16px;

            Text {
                text: @tr("Name: {}", root.name);
                font-italic: true;
            }

            Text {
                text: @tr("Author: {}", root.author);
                font-italic: true;
            }

            Text {
                text: @tr("E-Mail: {}", root.email);
                font-italic: true;
            }
        }
    }
}
