import { VerticalBox, Palette } from "std-widgets.slint";
export component ProjectInfoPanel inherits Rectangle {
    in property <string> name;
    in property <string> author;
    in property <string> email;

    height: 150px;
    width: 350px;

    background: Palette.alternate-background;

    VerticalLayout {
        alignment: start;
        padding: 4px;
        Text {
            text: @tr("Project information");
            font-size: 20px;
        }

        VerticalBox {
            padding: 16px;

            Text {
                text: @tr("Name: {}", root.name);
                font-italic: true;
            }

            Text {
                text: @tr("Author: {}", root.author);
                font-italic: true;
            }

            Text {
                text: @tr("E-Mail: {}", root.email);
                font-italic: true;
            }
        }
    }
}
