/**
 * Copyright (C) 2026 ZIMO Elektronik
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published
 * by the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program. If not, see <https://gnu.org>.
 *
 *
 *
 *
 *
 * Soundload page component
 *
 * \file    ui/soundload/soundload-page.slint
 * \author  Jonas Gahlert
 * \date    01.10.2026
 */

import {
    Button,
    VerticalBox,
    HorizontalBox,
    ComboBox,
    Palette,
} from "std-widgets.slint";
import { ProgressPopup } from "../progress/progress-popup.slint";
import { ProgressViewContext } from "../progress/progress-context.slint";
import { ModeSelector, SoundLoadMode, ModeSelector } from "mode-selector.slint";
import { HelpModeButton } from "../utility/help-popup/help-mode-button.slint";
import {
    OptionLevelSelector,
    OptionLevel,
} from "../utility/option-level-selector/option-level-selector.slint";
import { HelpPopup } from "../utility/help-popup/help-popup.slint";
import { ProjectInfoPanel } from "project-info.slint";

// Re-export
export { SoundLoadMode }
export component SoundLoadPage inherits Rectangle {
    in-out property <SoundLoadMode> mode: SoundLoadMode.ZUSI;

    property <OptionLevel> option-level;

    in property <bool> has-file: false;

    in property <string> project-name;
    in property <string> project-author;
    in property <string> project-email;

    callback choose-file();
    callback start-process();

    HorizontalLayout {
        alignment: LayoutAlignment.space-between;
        spacing: 5px;

        VerticalLayout {
            padding: 20px;
            spacing: 15px;
            alignment: start;

            HorizontalLayout {
                spacing: 16px;
                alignment: start;

                Text {
                    text: @tr("SoundLoad");
                    font-size: 20px;
                    color: Palette.foreground;
                }

                help-mode-button := HelpModeButton { }
            }

            HorizontalLayout {
                spacing: 16px;
                alignment: start;

                HelpPopup {
                    help-text: @tr("Opens a file dialog and requires you to choose an update file (.zpp)");
                    visible: help-mode-button.help-mode;
                }

                Button {
                    text: @tr("Choose file");
                    // Deaktivieren, wenn der Prozess bereits läuft
                    enabled: !ProgressViewContext.is-process-running;
                    clicked => {
                        root.choose-file();
                    }
                }
            }

            // Start-Button
            HorizontalLayout {
                spacing: 16px;
                alignment: start;

                HelpPopup {
                    help-text: @tr("Begin the soundload procedure. Ensure, that the decoder is properly connected to the update device before clicking here");
                    visible: help-mode-button.help-mode;
                }

                Button {
                    text: @tr("Start soundload");
                    // Aktiv, wenn eine Datei existiert UND kein Update läuft
                    enabled: root.has-file && !ProgressViewContext.is-process-running;
                    clicked => {
                        root.start-process();
                    }
                }
            }

            HorizontalLayout {
                spacing: 16px;
                alignment: start;

                HelpPopup {
                    help-text: @tr("Choose the entry used to begin the update sequence.");
                    visible: help-mode-button.help-mode;
                }

                ModeSelector {
                    selected-mode <=> root.mode;
                }
            }
        }

        if root.has-file: VerticalBox {
            padding: 20px;
            ProjectInfoPanel {
                name: root.project-name;
                author: root.project-author;
                email: root.project-email;
            }
        }
    }

    // Dock progress at the bottom
    VerticalLayout {
        alignment: end;
        ProgressPopup { }
    }
}
