import {
    Button,
    VerticalBox,
    HorizontalBox,
    ComboBox,
} from "std-widgets.slint";
import { ProgressPopup } from "../progress/progress_popup.slint";
import { ProgressViewContext } from "../progress/progress_context.slint";
import { ModeSelector, SoundLoadMode, ModeSelector } from "mode_selector.slint";
import { HelpModeButton } from "../utility/help_popup/help_mode_button.slint";
import {
    OptionLevelSelector,
    OptionLevel,
} from "../utility/option_level_selector/option_level_selector.slint";
import { HelpPopup } from "../utility/help_popup/help_popup.slint";
import { ProjectInfoPanel } from "project_info.slint";

// Re-export
export { SoundLoadMode }


export component SoundLoadPage inherits Rectangle {
    in-out property <SoundLoadMode> mode: SoundLoadMode.ZUSI;

    property <OptionLevel> option-level;

    in property <bool> has-file: false;

    in property <string> project-name;
    in property <string> project-author;
    in property <string> project-email;

    callback choose-file();
    callback start-process();

    HorizontalLayout {
        alignment: LayoutAlignment.space-between;
        spacing: 5px;

        VerticalLayout {
            padding: 20px;
            spacing: 15px;
            alignment: start;

            HorizontalLayout {
                spacing: 16px;
                alignment: start;

                Text {
                    text: "SoundLoad";
                    font-size: 20px;
                    color: #000000;
                }

                help-mode-button := HelpModeButton { }
            }

            HorizontalLayout {
                spacing: 16px;
                alignment: start;

                HelpPopup {
                    help-text: "Opens a file dialog and requires you to choose an update file (.zpp)";
                    visible: help-mode-button.help-mode;
                }

                Button {
                    text: "Choose file";
                    // Deaktivieren, wenn der Prozess bereits läuft
                    enabled: !ProgressViewContext.is-process-running;
                    clicked => {
                        root.choose-file();
                    }
                }
            }

            // Start-Button
            HorizontalLayout {
                spacing: 16px;
                alignment: start;

                HelpPopup {
                    help-text: "Begin the soundload procedure. Ensure, that the decoder is properly connected to the update device before clicking here";
                    visible: help-mode-button.help-mode;
                }

                Button {
                    text: "Start soundload";
                    // Aktiv, wenn eine Datei existiert UND kein Update läuft
                    enabled: root.has-file && !ProgressViewContext.is-process-running;
                    clicked => {
                        root.start-process();
                    }
                }
            }

            HorizontalLayout {
                spacing: 16px;
                alignment: start;

                HelpPopup {
                    help-text: "Choose the entry used to begin the update sequence.";
                    visible: help-mode-button.help-mode;
                }

                ModeSelector {
                    selected-mode <=> root.mode;
                }
            }
        }

        if root.has-file: VerticalBox {
            padding: 20px;
            ProjectInfoPanel {
                name: root.project-name;
                author: root.project-author;
                email: root.project-email;
            }
        }
    }

    // Dock progress at the bottom
    VerticalLayout {
        alignment: end;
        ProgressPopup { }
    }
}
