import {
    Button,
    VerticalBox,
    HorizontalBox,
    ComboBox,
} from "std-widgets.slint";
import { ProgressPopup } from "../progress/progress_popup.slint";
import { ProgressViewContext } from "../progress/progress_context.slint";

export enum SoundLoadMode {
    ZUSI, 
    MDU,
}

export component SoundLoadPage inherits Rectangle {
    in-out property <SoundLoadMode> mode: SoundLoadMode.ZUSI;
    callback mode-changed(SoundLoadMode);

    in property <bool> has-file: false;
    in property <string> file-path: "";

    callback choose-file();
    callback start-process();

    VerticalLayout {
        alignment: LayoutAlignment.space-between;
        spacing: 5px;

        VerticalBox {
            padding: 20px;
            spacing: 15px;
            alignment: start;

            HorizontalLayout {
                Text {
                    text: "SoundLoad";
                    font-size: 20px;
                    color: #000000;
                }

                ComboBox {
                    model: ["ZUSI", "MDU"];

                    current-index: root.mode == SoundLoadMode.ZUSI ? 0 : 1;

                    selected(current-value) => {
                        if (current-value == 0) {
                            root.mode = SoundLoadMode.ZUSI;
                        } else {
                            root.mode = SoundLoadMode.MDU;
                        }

                        root.mode-changed(root.mode);
                    }
                }
            }

            // Bereich für die Dateiauswahl
            HorizontalBox {
                spacing: 10px;
                alignment: start;

                Button {
                    text: "Choose file";
                // Deaktivieren, wenn der Prozess bereits läuft
                enabled: !ProgressViewContext.is-process-running;
                    clicked => {
                        root.choose-file();
                    }
                }

                Text {
                    text: root.file-path == "" ? "No file selected" : root.file-path;
                    vertical-alignment: center;
                    color: root.has-file ? #2c3e50 : #7f8c8d;
                    font-italic: !root.has-file;
                }
            }

            // Start-Button
            HorizontalBox {
                alignment: start;

                Button {
                    text: "Start update";
                // Aktiv, wenn eine Datei existiert UND kein Update läuft
                enabled: root.has-file && !ProgressViewContext.is-process-running;
                    clicked => {
                        root.start-process();
                    }
                }
            }
        }

        VerticalLayout {
            padding-top: 20px;
            padding-right: 10px; // Avoid placing this on the edge of the window
            alignment: LayoutAlignment.start;

            ProgressPopup { }
        }
    }
}
