/**
 * Copyright (C) 2026 ZIMO Elektronik
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published
 * by the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program. If not, see <https://gnu.org>.
 *
 *
 *
 *
 *
 * Dependency badge component
 *
 * \file    ui/utility/dependency-badge/dependency-badge.slint
 * \author  Jonas Gahlert
 * \date    01.10.2026
 */

export component DependencyBadge {
    in property <string> name: "libdependency";
    in property <string> link: "https://anicedependency.xyz";
    in property <string> license: "NGL3.0 (Nice-Guy-License 3.0";

    HorizontalLayout {
        alignment: start;
        padding: 2px;
        Rectangle {
            vertical-stretch: 1;
            width: 100px;
            Text {
                width: parent.width;
                height: parent.height;
                horizontal-alignment: end;
                vertical-alignment: top;
                text: root.name;
            }

            TouchArea {
                clicked => {
                    Platform.open-url(link);
                }
            }
        }

        Rectangle { // Spacer
            width: 10px;
        }

        Text {
            text: root.license;
        }
    }
}
