import { ComboBox } from "std-widgets.slint";
import { EntryType } from "entry.slint";
export { EntryType }

export component EntrySelector inherits Rectangle {
    in-out property <EntryType> type;

    preferred-height: layout.preferred-height;
    preferred-width: layout.preferred-width;

    layout := HorizontalLayout {
        alignment: start;
        spacing: 10px;

        Text {
            text: "Entry type";
            vertical-alignment: center;
            font-size: 16px;
        }

        ComboBox {
            model: ["MDU", "DCC"];

            current-index: root.type == EntryType.MDU ? 0 : 1;

            selected(current-value) => {
                if (current-value == 0) {
                    root.type = EntryType.MDU;
                } else {
                    root.type = EntryType.DCC;
                }
            }
        }
    }
}
