/**
 * Copyright (C) 2026 ZIMO Elektronik
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published
 * by the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program. If not, see <https://gnu.org>.
 *
 *
 *
 *
 *
 * Entry selector component
 *
 * \file    ui/update/entry-selector.slint
 * \author  Jonas Gahlert
 * \date    01.10.2026
 */

import { ComboBox } from "std-widgets.slint";
import { EntryType } from "entry.slint";
export { EntryType }
export component EntrySelector inherits Rectangle {
    in-out property <EntryType> type;

    preferred-height: layout.preferred-height;
    preferred-width: layout.preferred-width;

    layout := HorizontalLayout {
        alignment: start;
        spacing: 10px;

        Text {
            text: @tr("Entry type");
            vertical-alignment: center;
            font-size: 16px;
        }

        ComboBox {
            model: ["MDU", "DCC"];

            current-index: root.type == EntryType.MDU ? 0 : 1;

            selected(current-value) => {
                if (current-value == 0) {
                    root.type = EntryType.MDU;
                } else {
                    root.type = EntryType.DCC;
                }
            }
        }
    }
}
