import { HorizontalBox, ComboBox } from "std-widgets.slint";
import { EntryType } from "entry.slint";

export component EntrySelector {
    in-out property <EntryType> mode;

    HorizontalBox {
        Text {
            text: "Entry type";
            vertical-alignment: center;
            font-size: 16px;
        }

        ComboBox {
            model: ["MDU", "DCC"];

            current-index: root.mode == EntryType.MDU ? 0 : 1;

            selected(current-value) => {
                if (current-value == 0) {
                    root.mode = EntryType.MDU;
                } else {
                    root.mode = EntryType.DCC;
                }
            }
        }
    }
}
