import { ScrollView } from "std-widgets.slint";
import { FirmwareAdapter } from "firmware.slint";
import { FirmwareEntry } from "firmware_entry.slint";

export component FirmwareSelector inherits Rectangle {
    in property <[FirmwareAdapter]> firmwares;

    height: 100%;
    width: 100%;

    //preferred-height: view.preferred-height;
    //preferred-width: view.preferred-width;

    view := ScrollView {
        height: 100%;

        layout := VerticalLayout {
            //spacing: 4px;

            FirmwareEntry {
                name: "Name";
                id: "ID";
                version: "Version";
                is-even: false;
                show-box: false;
            }

            for fw[idx] in root.firmwares: FirmwareEntry {
                name: fw.decoder-name;
                id: fw.decoder-id[3] + "." + fw.decoder-id[2] + "." + fw.decoder-id[1] + "." + fw.decoder-id[0];
                version: fw.major-version + "." + fw.minor-version;

                is-even: idx.mod(2) == 0;

                selected(selected) => {
                    fw.selected = selected;
                }
            }
        }
    }
}
