/**
 * Copyright (C) 2026 ZIMO Elektronik
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published
 * by the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program. If not, see <https://gnu.org>.
 *
 *
 *
 *
 *
 * Firmware selector component
 *
 * \file    ui/update/firmware-selector.slint
 * \author  Jonas Gahlert
 * \date    01.10.2026
 */

import { ScrollView, VerticalBox } from "std-widgets.slint";
import { FirmwareAdapter } from "firmware.slint";
import { FirmwareEntry } from "firmware-entry.slint";
import { HelpPopup } from "../utility/help-popup/help-popup.slint";

export component FirmwareSelector inherits Rectangle {
    in property <[FirmwareAdapter]> firmwares;

    in property <bool> help-mode;
    vertical-stretch: 1;
    horizontal-stretch: 1;

    HelpPopup {
        help-text: "Choose a selection of decoder IDs (preferably your model) for the update. This can help if the update repeatedly fails at the entry";
        visible: root.help-mode;

        // This is placed relative to the center of the list container (the Rectangle). 
        // Following its center is placed on the upper left edge of the parent (the Rectangle) 
        // and then a minor correction is done. No, I'm not happy with this but it works and 
        // should be rather stable (give or take a vew pixels) 
        // This only works btw because the anchor withing a rectangle by default is it's center.
        x: 0 - parent.width / 2 - 16px;
        y: 0 - parent.height / 2 + 16px;
    }

    outer-layout := VerticalLayout {
        width: 100%;
        height: 100%;

        padding-bottom: 30px;

        FirmwareEntry {
            name: @tr("Name");
            id: @tr("ID");
            version: @tr("Version");
            is-even: false;
            show-box: false;
        }

        Rectangle {
            height: 2px;
            background: black;
        }

        view := ScrollView {
            height: 100%;
            preferred-width: layout.preferred-width;

            layout := VerticalLayout {
                for fw[idx] in root.firmwares: FirmwareEntry {
                    name: fw.decoder-name;
                    id: fw.decoder-id[3] + "." + fw.decoder-id[2] + "." + fw.decoder-id[1] + "." + fw.decoder-id[0];
                    version: fw.major-version + "." + fw.minor-version;

                    is-even: idx.mod(2) == 0;

                    selected(selected) => {
                        fw.selected = selected;
                    }
                }
            }
        }
    }
}
