/**
 * Copyright (C) 2026 ZIMO Elektronik
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published
 * by the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program. If not, see <https://gnu.org>.
 *
 *
 *
 *
 *
 * Firmware entry component
 *
 * \file    ui/update/firmware-entry.slint
 * \author  Jonas Gahlert
 * \date    01.10.2026
 */

import { FirmwareAdapter } from "firmware.slint";
import { HorizontalBox, CheckBox, Palette } from "std-widgets.slint";

export component FirmwareEntry {
    in property <string> name: "MS9000";
    in property <string> id: "0.0.0.0";
    in property <string> version: "0.0";

    in property <bool> is-even: true;
    in property <bool> show-box: true;

    property <color> even-background: Palette.color-scheme == ColorScheme.dark ? Colors.black : Colors.white;
    property <color> uneven-background: Palette.color-scheme == ColorScheme.dark ? Colors.transparent : Colors.lightgray;

    callback selected(bool);

    Rectangle {
        background: is-even ? even-background : uneven-background;
        max-width: 300px;

        HorizontalLayout {
            alignment: start;
            spacing: 10px;
            padding: 5px;

            select := CheckBox {
                visible: root.show-box;
                changed checked => root.selected(self.checked);
            }

            name-text := Text {
                text: root.name;
                width: 80px;
            }

            id-text := Text {
                text: root.id;
                width: 100px;
            }

            version-text := Text {
                text: root.version;
                width: 100px;
            }
        }
    }
}
