import { Button, VerticalBox, HorizontalBox } from "std-widgets.slint";
import { ProgressPopup } from "../progress/progress_popup.slint";
import { ProgressViewContext } from "../progress/progress_context.slint";
import { EntrySelector } from "entry_selector.slint";
import { EntryType } from "entry.slint";
import { FirmwareSelector } from "firmware_selector.slint";
import { FirmwareAdapter } from "firmware.slint";

export component UpdatePage inherits Rectangle {
    in property <bool> has-file: false;
    in property <string> file-path: "";

    in property <[FirmwareAdapter]> firmwares;

    in-out property <EntryType> entry-type;

    callback choose-file();
    callback start-process();

    VerticalLayout {
        alignment: LayoutAlignment.space-between;

        VerticalBox {
            padding: 20px;
            spacing: 15px;
            alignment: start;

            Text {
                text: "Update";
                font-size: 20px;
                color: #000000;
            }

            // Bereich für die Dateiauswahl
            HorizontalBox {
                spacing: 10px;
                alignment: start;

                Button {
                    text: "Choose file";
                // Deaktivieren, wenn der Prozess bereits läuft
                enabled: !ProgressViewContext.is-process-running;
                    clicked => {
                        root.choose-file();
                    }
                }

                Text {
                    text: root.file-path == "" ? "No file selected" : root.file-path;
                    vertical-alignment: center;
                    color: root.has-file ? #2c3e50 : #7f8c8d;
                    font-italic: !root.has-file;
                }
            }

            // Start-Button
            HorizontalBox {
                alignment: start;

                Button {
                    text: "Start update";
                // Aktiv, wenn eine Datei existiert UND kein Update läuft
                enabled: root.has-file && !ProgressViewContext.is-process-running;
                    clicked => {
                        root.start-process();
                    }
                }
            }

            EntrySelector {
                type <=> root.entry-type;
            }

            FirmwareSelector {
                firmwares <=> root.firmwares;
            }
        }

        VerticalLayout {
            padding-top: 20px;
            padding-right: 10px; // Avoid placing this on the edge of the window
            alignment: LayoutAlignment.start;

            ProgressPopup { }
        }
    }
}
