/**
 * Copyright (C) 2026 ZIMO Elektronik
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published
 * by the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program. If not, see <https://gnu.org>.
 *
 *
 *
 *
 *
 * Progress bar component
 *
 * \file    ui/progress/progress-bar.slint
 * \author  Jonas Gahlert
 * \date    01.10.2026
 */

import { Palette } from "std-widgets.slint";
export component ProgressBar inherits Rectangle {

    in property <float> progress;
    in property <bool> smoothing: false;

    height: 25px;
    width: 100%;

    border-color: Palette.color-scheme == ColorScheme.dark ? Colors.darkslategray : Colors.silver;
    border-width: 1px;
    background: Palette.control-background;
    clip: true;

    Rectangle {
        x: 0;
        y: 0;

        width: parent.width * root.progress;
        height: 100%;
        background: Palette.color-scheme == ColorScheme.dark ? Colors.darkslategray : Colors.silver;

        animate width {
            duration: root.smoothing ? 150ms : 0ms;
            easing: ease-in-out;
        }
    }
}
