/**
 * Copyright (C) 2026 ZIMO Elektronik
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published
 * by the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program. If not, see <https://gnu.org>.
 *
 *
 *
 *
 *
 * Progress popup component
 *
 * \file    ui/progress/progress-popup.slint
 * \author  Jonas Gahlert
 * \date    01.10.2026
 */

import { Button, ProgressIndicator, VerticalBox } from "std-widgets.slint";
import { ProgressViewContext } from "progress-context.slint";
import { ProgressPanel } from "progress-panel.slint";
import { ProgressBar } from "progress-bar.slint";

export component ProgressPopup inherits VerticalBox {
    padding: 10px;
    spacing: 10px;
    vertical-stretch: 0;

    if (ProgressViewContext.is-open): ProgressPanel {
        close-clicked => {
            ProgressViewContext.is-open = false;
        }
        abort-clicked => ProgressViewContext.abort();
    }

    if (!ProgressViewContext.is-open && ProgressViewContext.is-process-running): TouchArea {
        height: 10px;
        bar := ProgressBar {
            preferred-height: 25px;
            height: 10px;
            width: 100%;
            progress <=> ProgressViewContext.progress;
        }

        clicked => {
            ProgressViewContext.is-open = !ProgressViewContext.is-open;
        }
    }
}
