/**
 * Copyright (C) 2026 ZIMO Elektronik
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published
 * by the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program. If not, see <https://gnu.org>.
 *
 *
 *
 *
 *
 * Progress panel component
 *
 * \file    ui/progress/progress-panel.slint
 * \author  Jonas Gahlert
 * \date    01.10.2026
 */

import {
    Button,
    VerticalBox,
    HorizontalBox,
    Palette,
} from "std-widgets.slint";
import { ProgressViewContext } from "progress-context.slint";
import { ProgressBar } from "progress-bar.slint";
import { StepText } from "dynamic/step-text.slint";
import { DeviceBadge } from "dynamic/device-badge.slint";

export component ProgressPanel {
    in property id <=> ProgressViewContext.id;
    in property device-string <=> ProgressViewContext.device_string;
    in property progress <=> ProgressViewContext.progress;
    in property time-estimate <=> ProgressViewContext.time-estimate;

    callback close-clicked();
    callback abort-clicked();

    Rectangle {
        background: Palette.color-scheme == ColorScheme.dark ? Colors.dimgray : Colors.lightgray;
        border-radius: 4px;
        border-width: 1px;
        border-color: Colors.teal;

        min-width: 300px;

        HorizontalLayout {
            VerticalBox {
                spacing: 10px;

                HorizontalLayout {
                    alignment: LayoutAlignment.space-between;

                    StepText {
                        id <=> root.id;
                    }

                    TouchArea {
                        Text {
                            text: "x";
                            font-size: 20px;
                        }

                        clicked => root.close-clicked();
                    }
                }

                Rectangle {
                    width: 100%;
                    preferred-height: progress-text.preferred-height + 5px;

                    ProgressBar {
                        progress <=> root.progress;
                        width: 100%;
                        preferred-height: progress-text.preferred-height + 5px;
                    }

                    progress-text := Text {
                        horizontal-alignment: center;
                        vertical-alignment: center;
                        text: Math.round(root.progress * 100) + "%";
                    }
                }

                HorizontalBox {
                    DeviceBadge {
                        device-string <=> root.device-string;
                    }
                }

                HorizontalBox {
                    alignment: space-between;

                    Text {
                        vertical-alignment: center;
                        text: @tr("Estimated time remaining: {}", root.time-estimate);
                    }

                    Button {
                        text: ProgressViewContext.is-process-running ? @tr("Abort") : @tr("OK");
                        clicked => {
                            if (ProgressViewContext.is-process-running) { root.abort-clicked(); }
                            else {
                                root.close-clicked();
                            }
                        }
                    }
                }
            }
        }
    }
}
