/**
 * Copyright (C) 2026 ZIMO Elektronik
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published
 * by the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program. If not, see <https://gnu.org>.
 *
 *
 *
 *
 *
 * Progress context
 *
 * \file    ui/progress/progress-context.slint
 * \author  Jonas Gahlert
 * \date    01.10.2026
 */

import { MessageIDAdapter } from "dynamic/step-text.slint";

export global ProgressViewContext {
    in property <bool> has-process; // For testing, reset when running
    in property <bool> is-process-running;

    in-out property <bool> is-open;
    in property <MessageIDAdapter> id;
    in property <string> device-string;
    in property <float> progress: 0.5;

    in property <string> time-estimate;

    callback abort();

    changed is-process-running => {
        if is-process-running {
            is-open = true;
        }
    }
}
