import {
    Button,
    VerticalBox,
    HorizontalBox,
    Palette,
} from "std-widgets.slint";
import { ProgressViewContext } from "progress_context.slint";
import { ProgressBar } from "progress_bar.slint";
import { StepText } from "dynamic/step_text.slint";
import { DeviceBadge } from "dynamic/device_badge.slint";

export component ProgressPanel {
    in property id <=> ProgressViewContext.id;
    in property device-string <=> ProgressViewContext.device_string;
    in property progress <=> ProgressViewContext.progress;
    in property time-estimate <=> ProgressViewContext.time-estimate;

    callback close-clicked();
    callback abort-clicked();

    Rectangle {
        background: Palette.color-scheme == ColorScheme.dark ? Colors.dimgray : Colors.lightgray;
        border-radius: 4px;
        border-width: 1px;
        border-color: Colors.teal;

        min-width: 300px;

        HorizontalLayout {
            VerticalBox {
                spacing: 10px;

                HorizontalLayout {
                    alignment: LayoutAlignment.space-between;

                    StepText {
                        id <=> root.id;
                    }

                    TouchArea {
                        Text {
                            text: "x";
                            font-size: 20px;
                        }

                        clicked => root.close-clicked();
                    }
                }

                Rectangle {
                    width: 100%;
                    preferred-height: progress-text.preferred-height + 5px;

                    ProgressBar {
                        progress <=> root.progress;
                        width: 100%;
                        preferred-height: progress-text.preferred-height + 5px;
                    }

                    progress-text := Text {
                        horizontal-alignment: center;
                        vertical-alignment: center;
                        text: Math.round(root.progress * 100) + "%";
                    }
                }

                HorizontalBox {
                    DeviceBadge {
                        device-string <=> root.device-string;
                    }
                }

                HorizontalBox {
                    alignment: space-between;

                    Text {
                        vertical-alignment: center;
                        text: @tr("Estimated time remaining: {}", root.time-estimate);
                    }

                    Button {
                        text: ProgressViewContext.is-process-running ? @tr("Abort") : @tr("OK");
                        clicked => {
                            root.abort-clicked();
                        }
                    }
                }
            }
        }
    }
}
