export global ProgressViewContext {
    in property <bool> has-process: true; // For testing, reset when running
    in property <bool> is-process-running;

    in-out property <bool> is-open: true;
    in property <string> step: "Imagine a step here";
    in property <float> progress: 0.5;

    in property <string> time-estimate;

    callback abort();

    changed is-process-running => {
        if is-process-running {
            is-open = true;
        }
    }
}
