export global ProgressViewContext {
    in property <bool> has-process: true; // For testing, reset when running
    in property <bool> is-process-running;

    in-out property <bool> is-open;

    in property <string> step;
    in property <float> progress;

    in property <string> time-estimate;

    callback abort();

    changed is-process-running => {
        if is-process-running {
            is-open = true;
        }
    }
}
