import { Palette } from "std-widgets.slint";
export component ProgressBar inherits Rectangle {

    in property <float> progress;
    in property <bool> smoothing: false;

    height: 25px;
    width: 100%;

    border-color: Palette.color-scheme == ColorScheme.dark ? Colors.darkslategray : Colors.silver;
    border-width: 1px;
    background: Palette.control-background;
    clip: true;

    Rectangle {
        x: 0;
        y: 0;

        width: parent.width * root.progress;
        height: 100%;
        background: Palette.color-scheme == ColorScheme.dark ? Colors.darkslategray : Colors.silver;

        animate width {
            duration: root.smoothing ? 150ms : 0ms;
            easing: ease-in-out;
        }
    }
}
