import { Button, ProgressIndicator } from "std-widgets.slint";
import { ProgressViewContext } from "progress_context.slint";
import { ProgressPanel } from "progress_panel.slint";
import { ProgressBar } from "progress_bar.slint";

export component ProgressPopup inherits VerticalLayout {
    alignment: LayoutAlignment.end;
    padding: 10px;
    spacing: 10px;

    if (ProgressViewContext.is-open): ProgressPanel {
        close-clicked => {
            ProgressViewContext.is-open = false;
        }
        abort-clicked => ProgressViewContext.abort();
    }

    if (!ProgressViewContext.is-open && ProgressViewContext.has-process): TouchArea {
        bar := ProgressBar {
            preferred-height: 25px;
            width: 100%;
            progress <=> ProgressViewContext.progress;
        }

        clicked => {
            ProgressViewContext.is-open = !ProgressViewContext.is-open;
        }
    }
}
