import {
    AboutSlint,
    HorizontalBox,
    Button,
    TabWidget,
    ScrollView,
    VerticalBox,
    Palette,
} from "std-widgets.slint";
import { AppContext } from "app_context.slint";
import {
    DependencyBadge,
} from "utility/dependency_badge/dependency_badge.slint";
export component AboutPage inherits Rectangle {
    callback open_website;
    callback open_support;
    callback report_bug;

    open_website => {
        Platform.open-url("https://zimo.at");
    }

    open_support => {
        Platform.open-url("https://www.zimo.at/web2010/sales/kundendienst.htm");
    }

    report_bug => {
        Platform.open-url("https://mantis.zimo.at");
    }

    VerticalLayout {
        alignment: LayoutAlignment.center;
        spacing: 4px;

        padding-left: 20px;
        padding-right: 20px;

        HorizontalBox {
            alignment: center;
            Rectangle {
                width: 160px;
                height: 100px;
                background: transparent;
                border-radius: 16px;

                Image {
                    source: @image-url("../data/zimo_logo.svg");
                    image-fit: ImageFit.contain;
                    width: parent.width;
                    height: parent.height;
                }
            }
        }

        Text {
            text: AppContext.tool-name-acronym;
            font-size: 28px;
            horizontal-alignment: center;
            color: Palette.color-scheme == ColorScheme.dark ? Colors.teal : Colors.blue;
        }

        Text {
            text: AppContext.tool-name;
            font-size: 22px;
            horizontal-alignment: center;
            color: Palette.color-scheme == ColorScheme.dark ? Colors.teal : Colors.blue;
        }

        Text {
            text: AppContext.tool-version;
            font-size: 12px;
            horizontal-alignment: center;
        }

        Text {
            text: AppContext.tool-description;
            font-size: 14px;
            horizontal-alignment: center;
            wrap: word-wrap;
        }

        Text {
            text: AppContext.cr-text;
            font-size: 10px;
            horizontal-alignment: center;
            wrap: word-wrap;
        }

        HorizontalLayout {
            alignment: center;
            spacing: 12px;
            padding: 8px;

            Button {
                text: @tr("Website");
                clicked => root.open_website();
            }

            Button {
                text: @tr("Support");
                clicked => root.open_support();
            }

            Button {
                text: @tr("Report bug");
                clicked => root.report_bug();
            }
        }

        Rectangle {
            height: 1px;
            background: black;
        }

        HorizontalBox {
            //alignment: center;
            height: 100px;
            width: 100%;
            AboutSlint { }

            ScrollView {

                VerticalLayout {
                    alignment: start;

                    DependencyBadge {
                        name: "libklug";
                        link: "https://zimo.at";
                        license: "LGPL3";
                    }

                    DependencyBadge {
                        name: "libusb";
                        link: "https://libusb.info";
                        license: "LGPL2.1";
                    }

                    DependencyBadge {
                        name: "libserialport";
                        link: "https://sigrok.org/wiki/Libserialport";
                        license: "LGPL3";
                    }

                    DependencyBadge {
                        name: "libintl";
                        link: "https://www.gnu.org/software/gettext";
                        license: "LGPL2.0";
                    }

                    DependencyBadge {
                        name: "tinyfiledialogs";
                        link: "https://sourceforge.net/projects/tinyfiledialogs/";
                        license: "ZLib";
                    }

                    DependencyBadge {
                        name: "slint";
                        link: "https://slint.dev";
                        license: "GPL3";
                    }
                }
            }
        }
    }
}
