import {
    Button,
    VerticalBox,
    GridBox,
    CheckBox,
    HorizontalBox,
    SpinBox,
} from "std-widgets.slint";
import { CvProgrammingPage } from "cv-programming.slint";
import { Cv } from "cv/cv.slint";

export component AppWindow inherits Window {
    in-out property <[Cv]> cv-list <=> cv-programmer.cv-list;

    callback cv-data-changed <=> cv-programmer.data_changed;

    HorizontalBox {
        cv-programmer := CvProgrammingPage { }
    }
}
