/**
 * Copyright (C) 2026 ZIMO Elektronik
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published
 * by the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program. If not, see <https://gnu.org>.
 *
 *
 *
 *
 *
 * App context
 *
 * \file    ui/app-context.slint
 * \author  Jonas Gahlert
 * \date    01.10.2026
 */

export global AppContext {
    in property <string> tool-name-acronym: "KLAUS";
    in property <string> tool-name: "KLUG Lite Audio-load and Update Software";
    in property <string> tool-version: @tr("Version: {}-{}", root.version, root.version_suffix);
    in property <string> tool-description: @tr("A simple (but experimental) tool to perform MS/MN/FS decoder-updates and soundload. This requires either a ZIMO KLUG or a ZIMO MXULF (OpenRemise planned)");

    in property <string> version: "0.0.0";
    in property <string> version_suffix: "experimental";

    in property <string> cr-text: @tr("Copyright © [2026] [ZIMO-Elektronik] \n This program is free software licensed under the GNU GPL v3. \n It is distributed without any warranty.");
}
