/**
 * Copyright (C) 2026 ZIMO Elektronik
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published
 * by the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program. If not, see <https://gnu.org>.
 *
 *
 *
 *
 *
 * App window
 *
 * \file    ui/app-window.slint
 * \author  Jonas Gahlert
 * \date    01.10.2026
 */

import { NavigationBar } from "navigation-bar.slint";
import { UpdatePage } from "update/update-page.slint";
import { SoundLoadPage, SoundLoadMode } from "soundload/soundload-page.slint";
import { AppPage } from "app-page.slint";
import { FirmwareAdapter } from "update/firmware.slint";
import { EntryType } from "update/entry.slint";
import { AboutPage } from "about-page.slint";
import { Palette } from "std-widgets.slint";

// Re-export context
import { ProgressViewContext } from "progress/progress-context.slint";
import { AppContext } from "app-context.slint";
import { MessageIDAdapter } from "progress/dynamic/step-text.slint";
export { ProgressViewContext, AppContext, MessageIDAdapter }
export component AppWindow inherits Window {
    title: AppContext.tool-name-acronym;
    width: 800px;
    height: 500px;

    in property <bool> has-file: false;

    in property <[FirmwareAdapter]> firmwares;
    in property <[FirmwareAdapter]> filtered-firmwares;
    in-out property <EntryType> entry-type;

    in-out property active-page <=> nav.active-page;

    in-out property <SoundLoadMode> sound-load-mode;
    in property <string> zpp_name;
    in property <string> zpp_author;
    in property <string> zpp_email;

    callback change_page(AppPage);

    callback choose_file();
    callback fetch_file();
    callback start_process();

    HorizontalLayout {

        // NavBar (left)
        nav := NavigationBar {
            change-page(page) => {
                root.change_page(page);
            }
        }

        // Page (right)
        Rectangle {
            background: Palette.background;

            if root.active-page == AppPage.Update: UpdatePage {
                has-file <=> root.has-file;
                firmwares <=> root.filtered_firmwares;
                entry-type <=> root.entry-type;
                choose-file => {
                    root.choose_file();
                }
                fetch-file => {
                    root.fetch_file();
                }
                start-process => {
                    root.start_process();
                }
            }

            if root.active-page == AppPage.Soundload: SoundLoadPage {
                has-file <=> root.has-file;
                mode <=> root.sound-load-mode;
                project-name: root.zpp_name;
                project-author: root.zpp_author;
                project-email: root.zpp_email;
                choose-file => {
                    root.choose_file();
                }
                start-process => {
                    root.start_process();
                }
            }

            if root.active-page == AppPage.About: AboutPage { }
        }
    }
}
