import { NavigationBar } from "navigation_bar.slint";
import { UpdatePage } from "update_page.slint";
import { SoundLoadPage, SoundLoadMode } from "soundload_page.slint";
import { CvProgrammerPage } from "cv_programmer_page.slint";
import { AppPage } from "types.slint";

export component AppWindow inherits Window {
    title: "Hier könnte ihre Werbung stehen";
    min-width: 800px;
    min-height: 500px;

    // Globale Properties für C++ Zugriff
    in property <bool> show-progress;
    in property <string> step-name: "Hier könnte ihre Werbung stehen";
    in property <float> progress-value: 0.0;
    in property <string> progress-estimate;

    in property <bool> has-file: false;
    in property <string> file-path: "";

    in-out property active-page <=> nav.active-page;

    in-out property <SoundLoadMode> sound-mode;

    // Globale Callbacks für C++ Registrierung
    callback change_page(AppPage);

    callback sound_mode_changed(SoundLoadMode);

    callback choose_file();
    callback start_process();
    callback abort_process();

    HorizontalLayout {
        // Linke Navigationsleiste
        nav := NavigationBar {
            change-page(page) => {
                root.change_page(page);
            }
        }

        // Rechter Inhaltsbereich mit dynamischen Seiten
        Rectangle {
            background: #ffffff;

            if root.active-page == AppPage.Update: UpdatePage {
                show-progress: root.show-progress;
                progress-value: root.progress-value;
                progress-estimate: root.progress-estimate;
                step-name: root.step-name;

                has-file: root.has-file;
                file-path: root.file-path;
                choose-file => {
                    root.choose_file();
                }
                start-process => {
                    root.start_process();
                }
                abort-process => {
                    root.abort-process();
                }
            }

            if root.active-page == AppPage.Soundload: SoundLoadPage {
                show-progress: root.show-progress;
                progress-value: root.progress-value;
                progress-estimate: root.progress-estimate;
                step-name: root.step-name;

                has-file: root.has-file;
                file-path: root.file-path;
                choose-file => {
                    root.choose_file();
                }
                start-process => {
                    root.start_process();
                }
                mode-changed(mode) => {
                    root.sound_mode_changed(mode);
                }
                abort-process => {
                    root.abort-process();
                }
            }

            if root.active-page == AppPage.CvProgrammer: CvProgrammerPage {
                show-progress: root.show-progress;
                progress-value: root.progress-value;
                step-name: root.step-name;
                abort-process => {
                    root.abort-process();
                }
            }
        }
    }
}
