export global AppContext {
    in property <image> logo;
    in property <string> tool-name: "Hier könnte ihre Werbung stehen";
    in property <string> tool-version: @tr("Imagine a very stable and complete version here");
    in property <string> tool-description: @tr("Imagine a very on-point description. With a second sentence of course. Maybe it is just long enough to force a line-break");

    in property <string> cr-text: @tr("A really good and complete copyright notice");
}
