export global AppContext {
    in property <string> tool-name-acronym: "KLAUS";
    in property <string> tool-name: "KLUG Lite Audio-load and Update Software";
    in property <string> tool-version: @tr("Version: {}-{}", root.version, root.version_suffix);
    in property <string> tool-description: @tr("A simple (but experimental) tool to perform MS/MN/FS decoder-updates and soundload. This requires either a ZIMO KLUG or a ZIMO MXULF (OpenRemise planned)");

    in property <string> version: "0.0.0";
    in property <string> version_suffix: "experimental";

    in property <string> cr-text: @tr("Copyright © [2026] [ZIMO-Elektronik] \n This program is free software licensed under the GNU GPL v3. \n It is distributed without any warranty.");
}
