export global AppContext {
    in property <image> logo: @image-url("../data/logo.png");
    in property <string> tool-name: "Hier könnte ihre Werbung stehen";
    in property <string> tool-version: @tr("Version: {}-{}", root.version, root.version_suffix);
    in property <string> tool-description: @tr("A simple (but experimental) tool to perform MS/MN/FS decoder-updates and soundload");

    in property <string> version: "0.0.0";
    in property <string> version_suffix: "experimental";

    in property <string> cr-text: @tr("A really good and complete copyright notice");
}
