import {
    Button,
    VerticalBox,
    GridBox,
    CheckBox,
    HorizontalBox,
    SpinBox,
} from "std-widgets.slint";
import { Cv } from "cv/cv.slint";
import { CvList } from "cv/cv_list.slint";

export component CvProgrammingPage inherits VerticalLayout {
    in-out property <[Cv]> cv-list;

    callback data_changed <=> cv-list-view.data_changed;

    padding: 10px;
    Text {
        text: "Listentest";
    }

    cv-list-view := CvList {
        cv-list: cv-list;
    }
}
