import { VerticalBox } from "std-widgets.slint";
import { ProgressPopup } from "progress/progress_popup.slint";

export component CvProgrammerPage {
    HorizontalLayout {
        alignment: LayoutAlignment.stretch;

        VerticalBox {
            padding: 20px;
            Text {
                text: "CvProgrammer Bereich";
                font-size: 20px;
                color: #000000;
            }

            Rectangle {
                vertical-stretch: 1;
            }
        }

        ProgressPopup { }
    }
}
