/**
 * Copyright (C) 2026 ZIMO Elektronik
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published
 * by the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program. If not, see <https://gnu.org>.
 *
 *
 *
 *
 *
 * Navigation bar component
 *
 * \file    ui/navigation-bar.slint
 * \author  Jonas Gahlert
 * \date    01.10.2026
 */

import { Button, VerticalBox, Palette } from "std-widgets.slint";
import { AppPage } from "app-page.slint";

export component NavigationBar {
    in-out property <AppPage> active-page: Update;

    callback change_page(AppPage);

    Rectangle {
        width: 180px;
        background: Palette.color-scheme == ColorScheme.dark ? Colors.black : darkslategray;

        VerticalBox {
            padding: 10px;
            spacing: 8px;
            alignment: start;

            Text {
                text: @tr("Navigation");
                color: white;
                font-size: 16px;
                horizontal-alignment: center;
            }

            Rectangle {
                height: 10px;
            }

            Button {
                text: @tr("Update");
                clicked => {
                    root.active-page = AppPage.Update;
                    root.change_page(root.active-page);
                }
            }

            Button {
                text: @tr("SoundLoad");
                clicked => {
                    root.active-page = AppPage.Soundload;
                    root.change_page(root.active-page);
                }
            }

            Rectangle {
                vertical-stretch: 1.0;
            }
        }

        VerticalBox {
            alignment: LayoutAlignment.end;

            Button {
                text: @tr("About");
                clicked => {
                    root.active-page = AppPage.About;
                    root.change_page(root.active-page);
                }
            }
        }
    }
}
