import {
    Button,
    VerticalBox,
    HorizontalBox,
    ProgressIndicator,
} from "std-widgets.slint";

export component ProgressPanel {
    in property <string> step-name: "Hier könnte ihre Werbung stehen";
    in property <float> progress-value: 0.0; // Wert zwischen 0.0 und 1.0
    callback abort-clicked();

    Rectangle {
        background: #f0f0f0;
        border-radius: 4px;
        border-width: 1px;
        border-color: #cccccc;

        VerticalBox {
            spacing: 10px;
            padding: 15px;

            Text {
                text: root.step-name;
                font-size: 14px;
                font-weight: 700;
                color: #333333;
            }

            ProgressIndicator {
                progress: root.progress-value;
            }

            HorizontalBox {
                alignment: end;
                Button {
                    text: "Abort";
                    clicked => {
                        root.abort-clicked();
                    }
                }
            }
        }
    }
}
