import {
    Button,
    VerticalBox,
    HorizontalBox,
    ProgressIndicator,
} from "std-widgets.slint";

export component ProgressPanel {
    in property <string> step-name: "Hier könnte ihre Werbung stehen";
    in property <float> progress-value: 0.0; // Wert zwischen 0.0 und 1.0
    in property <string> estimate;

    callback abort-clicked();

    Rectangle {
        background: #f0f0f0;
        border-radius: 4px;
        border-width: 1px;
        border-color: #cccccc;

        VerticalBox {
            spacing: 10px;
            padding: 15px;

            Text {
                text: root.step-name;
                font-size: 14px;
                font-weight: 700;
                color: #333333;
            }

            Rectangle {
                //width: 100%;
                //height: 100%;
                width: 100%;
                preferred-height: progress-text.preferred-height + 5px;
                ProgressIndicator {
                    progress: root.progress-value;
                    width: 90%;
                    preferred-height: progress-text.preferred-height + 5px;
                }

                progress-text := Text {
                    horizontal-alignment: center;
                    vertical-alignment: center;
                    text: Math.round(root.progress-value * 100) + "%";
                }
            }

            Text {
                text: "Estimated time remaining: " + root.estimate;
            }

            HorizontalBox {
                alignment: end;
                Button {
                    text: "Abort";
                    clicked => {
                        root.abort-clicked();
                    }
                }
            }
        }
    }
}
