import {
    Button,
    VerticalBox,
    GridBox,
    CheckBox,
    HorizontalBox,
    SpinBox,
} from "std-widgets.slint";
import { ProgressView } from "progress/progress-view.slint";

export component UpdatePage inherits Rectangle {
    in property progress-title-text <=> progress.title_text;
    in property progress-step-text <=> progress.step_text;
    in property progress-progress <=> progress.progress;

    callback start-clicked <=> start.clicked;
    callback abort-clicked <=> abort.clicked;

    preferred-height: layout.preferred-height;
    preferred-width: layout.preferred-width;

    layout := HorizontalLayout {

        start := Button {
            text: "Start Update";
        }

        abort := Button {
            text: "Abort";
        }

        progress := ProgressView { }
    }
}
